[package]
name = "core-bridge-hello-world"
description = "Core Bridge Hello World"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["localnet"]
localnet = ["wormhole-core-bridge-solana/localnet"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies.wormhole-core-bridge-solana]
path = "../../programs/core-bridge"
features = ["cpi"]
default-features = false

[dependencies]
anchor-lang.workspace = true
