[package]
name = "wormhole-mock-cpi-solana"
description = "Wormhole Mock CPI Program for Solana"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["localnet"]
localnet = ["core-bridge-program/localnet", "token-bridge-program/localnet"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies.core-bridge-program]
path = "../core-bridge"
package = "wormhole-core-bridge-solana"
features = ["cpi"]
default-features = false

[dependencies.token-bridge-program]
path = "../token-bridge"
package = "wormhole-token-bridge-solana"
features = ["cpi"]
default-features = false

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
